#!/bin/bash
  #####################################################################################
  #### SUPORTE REGIONAL - PE/PB/AL/RN
  #####################################################################################
a='\033[1;33m'     # Amarelo
p='\033[0;35m'     # Purple
v="\033[0;31m"     #vermelho
vr="\033[01;32m"   #Verde
br="\033[0;37m"    #Branco
v1="\033[0;32m"    #Verde escuro
v2="\033[1;32m"    #verde claro
end='\033[0m'
##############################
logo () {
  clear
echo -e "${v1} __     ___   _  ____    ______ ____  _   _ 
\ \   / / \ | |/ ___|  / / ___/ ___|| | | |
 \ \ / /|  \| | |     / /\___ \___ \| |_| |
  \ V / | |\  | |___ / /  ___) |__) |  _  |
   \_/  |_| \_|\____/_/  |____/____/|_| |_|
   ${p}By: Nilsonlinux
   ${v1}Instalação e configuração.
   VNC Server e SSH + Atalhos. Para Linux Mint ${end}"
 }
##############################
logo
echo -e "${vr}Copiando atalhos pra Área de Trabalho.${end}"
echo " ------------------------------------- "
if [ -e "$HOME/.icons" ]
then
echo " Diretório ja existe. Prosseguindo com a instalação..."
else
mkdir $HOME/.icons
fi

mkdir $HOME/.local/comandos
cp $HOME/x11vnc/comandos/* $HOME/.local/comandos/
chmod +x $HOME/.local/comandos/*

cp $HOME/x11vnc/icons/* $HOME/.icons/
cp $HOME/x11vnc/Atalhos/* Área\ de\ Trabalho/
sudo chmod +x Área\ de\ Trabalho/*
rm -rf $HOME/x11vnc
echo -e "${p}INSTALANDO PACOTES...${end}"
sudo apt update && sudo apt install yad x11vnc freerdp2-x11 rdesktop openssh-server
logo
echo " ------------------------------------- "
sudo systemctl enable ssh
sudo systemctl start ssh
sudo ufw allow ssh
echo " ------------------------------------- "
echo "Criando diretório em /etc/x11vnc..." 
if [ -e "/etc/x11vnc" ]
then
echo " Diretório ja existe. Prosseguindo com a instalação..."
else
echo -e "${e} Criando o diretório"
sudo mkdir /etc/x11vnc
fi
echo " ------------------------------------- "
echo -e ${a}"Informe a senha de acesso para quando for fazer o acesso VNC nesta máquina...${end}"
echo -e "$v1-------------------------------------"
sudo x11vnc --storepasswd /etc/x11vnc/vncpwd 
echo -e "${br}Copiando arquivo de configuração...${end}"
sudo cp x11vnc/x11vnc.service /lib/systemd/system/
echo -e "${vr}Arquivo copiado...${end}"
echo "Configurando inicialização automática..."
echo "Configurando daemon-reload..."
sudo systemctl daemon-reload 
sudo systemctl enable x11vnc.service
sudo systemctl start x11vnc.service
echo -e "${vr} Instalação concluída. ${end}"
echo " ------------------------------------- "
IP=$(hostname -I)
echo "IP da Máquina 🌐: ${IP}" 
echo " ------------------------------------- "
